# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'GRS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'RSKImageCropper'
pod 'QBImagePickerController'


  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

end

target 'GRS-tvOS' do


end
