# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'GRS' do
  pod 'AppCenterReactNativeShared', '~> 1.9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'RSKImageCropper'
pod 'QBImagePickerController'


  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'
pod 'RNSVG', :path => '../node_modules/react-native-svg'


  platform :ios, '9.0'
end

target 'GRS-tvOS' do


end
