# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GRS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


end

target 'GRS-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GRS-tvOS

  target 'GRS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
